### PR TITLE
[feature #162724582] create a red-flag record

### PR DESCRIPTION
**Pull request by noahkalyesubula**
Hello there, Kindly review my api end-points .

### CODE REVIEW

**Comment by KapsonLabs** [comment]
Your OOP and MVC is quite clean. Am inspired.

**Comment by noahkalyesubula** [comment]
@KapsonLabs Thanks

**Comment by bekeplar** [comment]
Good work. Though read about the .gitignore filr

**Comment by noahkalyesubula** [comment]
@bekeplar thanks for your review. Will fix that

**Pull request merged**
